robot_config: robot/crazyfile_config.yaml

simulation:
  duration: 0.0
  dt: 0.002
  print_interval: 0.0
  track_camera_name: track

viewer:
  enabled: true
  fallback_to_headless: false
  mjui_enabled: true
  vsync: true
  show_mode_state_overlay: true

ros2:
  node_name: sim_bridge
  use_sim_time: true
  publish_rate_hz: 100.0
  command_timeout: 0.5
  publish_tf: true
  publish_clock: true
