robot_config: robot/scout_v2_config.yaml

simulation:
  duration: 0.0
  dt: 0.001
  print_interval: 0.0
  track_camera_name: "free"

viewer:
  enabled: true
  fallback_to_headless: true
  mjui_enabled: true
  vsync: true

ros2:
  node_name: scout_sim_bridge
  use_sim_time: true
  publish_rate_hz: 100.0
  command_timeout: 0.5
  publish_tf: true
  publish_clock: true
